server:
  port: 3344

spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/brooksjang/springcloud-config.git
          search-paths:
            - springcloud-config
      label: master
  rabbitmq:
    host: 192.168.126.129
    port: 5672
    username: admin
    password: 123456

#Eureka的配置，服务注册到那里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
#      ,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ #Eureka集群配置
  instance:
    instance-id: spring-cloud-config-3344 #修改Eureka监控页面的默认描述信息

#info配置，完善Eureka页面监控信息
info:
  app.name: Spring-Cloud-Config-Server
  company.name: AsiaInfo
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'

